# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Imagine Learning Web Styles
email: katrialynn18@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Imagine Learning web style guide for all Imagine Learning domain websites. It includes examples and demo code for web elements, fonts, colors, and Vue.js components.
baseurl: "/web-styles" # the subpath of your site, e.g. /blog
url: "https://katrialesser.github.io/" # the base hostname & protocol for your site
lang: en # specify content language
twitter_username: katria_lesser
github_username:  katrialesser

# Build settings
markdown: kramdown
exclude: ["src",
          "test",
          "node_modules",
          "package.json"] # Don't forget that Jekyll automatically
                          # excludes files with a dot prefix
compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []
